spring:

  # DB
  data:
    redis:
      host: localhost
      port: 6379

# chat gpt key
openai:
  api:
    key: ${OPENAI_API_KEY}

cloud:
  # S3
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false