spring:

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  # ElastiCache
  data:
    redis:
      host:
      port: 6379


cloud:

  # S3
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false


# chat gpt key
openai:
  api:
    key:


logging:
  level:
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG