spring:

  # DB
  datasource:
    url:
    username:
    password:

  # ElastiCache
  data:
    redis:
      host:
      port:

  # JWT
  security:
    jwt:
      secret-key:
      access:
        expiration: 3600 # 액세스 토큰 만료 시간 (초 단위)
      refresh:
        expiration: 604800 # 리프레시 토큰 만료 시간 (초 단위, 7일)


cloud:

  # S3
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false


# chat gpt key
openai:
  api:
    key:


logging:
  level:
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG