spring:

  # DB
  data:
    redis:
      host: localhost
      port: 6379

  security:
    jwt:
      secretKey: daccaf8d974dc147519ea15f6c3ae221b57a6ef8fa7508e7eca7e4acc863a6a2972ffd261e05dbe48479dd8e91186e5aaf720ffc223d29558848ada33ca48e07
      access:
        expiration: 3600 # 액세스 토큰 만료 시간 (초 단위)
      refresh:
        expiration: 604800 # 리프레시 토큰 만료 시간 (초 단위, 7일)

# chat gpt key
openai:
  api:
    key: ${OPENAI_API_KEY}